store/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from store import views

app_name = "store"


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("add/<slug:slug>/", views.add_to_cart, name="add_to_cart"),
    path("remove/<slug:slug>/", views.remove_from_cart, name="remove_from_cart"),
    path(
        "products/<slug:slug>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("category/<slug:slug>/", views.CategoryView.as_view(), name="category"),
    path("cart/", views.CartView.as_view(), name="cart_view"),
    path("checkout/", views.OrderCheckoutView.as_view(), name="checkout_view"),
    path("viewordertest/", views.view_orders, name="orders_view"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, include
from store import views
from user import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_settings/', views.UserSettingsView.as_view(), name='user_settings'),
]

webshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

import store.views

urlpatterns = [
    path('', store.views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('store/', include('store.urls', namespace='store')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls', namespace='user')),
    path('oauth/', include('social_django.urls', namespace='social'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/includes/navbar.html
{% load crispy_forms_filters %}
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid mt-auto mb-auto">
    <a class="navbar-brand" href="{% url 'store:index' %}">My Shop</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'store:product_list' %}">Products</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
      </ul>
      {% if search_form %}
        <!-- Centered search form -->
        <form id="search_form" class="w-auto d-flex" action="">
          {{ search_form }}
          <button form="search_form" class="btn btn-outline-success btn-block" type="submit">Search</button>
        </form>
      {% endif %}


      {#            <form class="d-flex w-auto" action="{% url 'store:product_list' %}">#}
      {#                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="search">#}
      {#                <button class="btn btn-outline-success" type="submit">Search</button>#}
      {#            </form>#}
      <div class="dropdown ms-auto mt-sm-3 mt-lg-auto d-flex">
        <!-- User cart (visible even if not authenticated) -->
        <a href="{% url 'store:cart_view' %}">
          <button type="button" class="btn btn-info me-2">Cart</button>
        </a>
        <!-- If authenticated show dropdown options -->
        {% if user.is_authenticated %}
          <!-- User profile dropdown -->
          <button class="btn btn-secondary dropdown-toggle d-flex justify-content-center align-items-center"
                  style="min-width: 120px;" type="button" id="userLoginButton" data-bs-toggle="dropdown"
                  aria-expanded="false">
            <span class="d-inline-block text-truncate align-baseline" style="max-width: 100px;">{% if user.first_name %}
              {{ user.first_name }}{% else %}{{ user.username }}{% endif %}</span>
          </button>
          <ul class="dropdown-menu" aria-labelledby="userLoginButton">
            <!-- User settings -->
            <a class="dropdown-item" href="{% url 'user:user_settings' %}">Settings</a>
            <li class="dropdown-divider"></li>
            <!-- User logout -->
            <form action="{% url 'logout' %}" method="post">
              {% csrf_token %}
              <button type="submit" class="dropdown-item">Log Out</button>
            </form>
          </ul>
          </div>
        {% else %}
          <!-- Sign In button -->
          <a href="{% url 'login' %}" class="btn btn-outline-light ms-auto">Sign In</a>
        {% endif %}
    </div>
  </div>
</nav>

templates/includes/pagination.html
{% if page_obj %}
  <div class="d-flex justify-content-center mt-3 fixed-bottom">
    <nav aria-label="Page navigation">
      <ul class="pagination">
        {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.previous_page_number }}">Prev</a>
          </li>
        {% endif %}
        <li class="page-item active">
          <span class="page-link bg-dark"
                style="border-color: gray">Page {{ page_obj.number }} of {{ paginator.num_pages }}</span>
        </li>
        {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link"
               href="?{% if query %}{{ query }}&{% endif %}page={{ page_obj.next_page_number }}">Next</a>
          </li>
        {% endif %}
      </ul>
    </nav>
  </div>
{% endif %}

templates/includes/product_card.html
{% load static %}
<div class="mt-4 ms-4">
  <div class="card rounded-1 shadow-sm h-100">
    <img src="{{ product.image.url }}" class="card-img-top" style="object-fit: cover; height: 200px;"
         alt="Product {{ product.name }}">
    <div class="card-body">
      <h5 class="card-title text-truncate" title="{{ product.name }}">{{ product.name }}</h5>
      <p class="card-text">{{ product.category.name }}</p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <a href="{% url 'store:product_detail' product.slug %}" class="btn btn-sm btn-outline-secondary">View</a>
          <a href="{% url 'store:add_to_cart' product.slug %}" class="btn btn-sm btn-outline-secondary">Add to Cart</a>
        </div>
        <div class="d-flex flex-column ps-2 text-center">
          {% if product.discount_price %}
            <small class="text-danger text-decoration-line-through">{{ product.price }}</small>
          {% endif %}
          <small class="fw-bolder">{{ product.get_price }}</small>
        </div>
      </div>
    </div>
  </div>
</div>