store/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from store import views

app_name = "store"


urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("add/<slug:slug>/", views.add_to_cart, name="add_to_cart"),
    path("remove/<slug:slug>/", views.remove_from_cart, name="remove_from_cart"),
    path(
        "products/<slug:slug>/",
        views.ProductDetailView.as_view(),
        name="product_detail",
    ),
    path("products/", views.ProductListView.as_view(), name="product_list"),
    path("category/<slug:slug>/", views.CategoryView.as_view(), name="category"),
    path("cart/", views.CartView.as_view(), name="cart_view"),
    path("checkout/", views.OrderCheckoutView.as_view(), name="checkout_view"),
    path("viewordertest/", views.view_orders, name="orders_view"),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path, include
from store import views
from user import views

app_name = 'user'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('user_settings/', views.UserSettingsView.as_view(), name='user_settings'),
]

webshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.shortcuts import redirect
from django.urls import path, include

import store.views

urlpatterns = [
    path('', store.views.IndexView.as_view()),
    path('admin/', admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
    path('store/', include('store.urls', namespace='store')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('user/', include('user.urls', namespace='user')),
    path('oauth/', include('social_django.urls', namespace='social'))

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

store/models.py
from datetime import datetime

from django.conf import settings
from django.db import models
from django.urls import reverse
from django.utils.text import slugify

# Create your models here.


class Category(models.Model):
    name = models.CharField(max_length=30)
    description = models.TextField(null=True, blank=True)
    slug = models.SlugField(null=True, blank=True)

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("store:category", kwargs={"slug": self.slug})

    def __str__(self):
        return self.name


class Product(models.Model):
    name = models.CharField(max_length=100)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    discount_price = models.DecimalField(
        blank=True, null=True, max_digits=10, decimal_places=2
    )
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    slug = models.SlugField(null=True, blank=True)
    description = models.TextField()
    image = models.ImageField(
        upload_to="products/", null=True, blank=True, default="products/default.jpg"
    )
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Product, self).save(*args, **kwargs)

    def get_price(self):
        return self.discount_price if self.discount_price else self.price

    def get_absolute_url(self):
        return reverse("store:product", kwargs={"slug": self.slug})


class CartProduct(models.Model):
    cart = models.ForeignKey("Cart", on_delete=models.CASCADE, null=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, null=True)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.product.name

    def get_true_price(self):
        return self.quantity * self.product.price

    def get_discount_price(self):
        return self.quantity * self.product.discount_price

    def get_amount_saved(self):
        return self.get_true_price() - self.get_discount_price()

    def get_price(self):
        if self.product.discount_price:
            return self.get_discount_price()
        return self.get_true_price()


class Cart(models.Model):
    user = models.ForeignKey(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE, null=True
    )
    session_key = models.CharField(max_length=40, null=True)
    products = models.ManyToManyField(Product, through="CartProduct")
    date_created = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)

    def get_total(self):
        total = 0
        for order_item in self.cartproduct_set.all():
            total += order_item.get_price()
        return total


class Order(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    phone = models.CharField(max_length=12, null=True)
    address = models.ForeignKey("Address", on_delete=models.CASCADE)

    status = models.CharField(
        max_length=20,
        choices=[
            ("PENDING", "Pending"),
            ("PROCESSING", "Processing"),
            ("SHIPPED", "Shipped"),
            ("DELIVERED", "Delivered"),
            ("CANCELED", "Canceled"),
        ],
        default="PENDING",
    )

    class Meta:
        ordering = ["-date_created"]


class Address(models.Model):
    street = models.CharField(max_length=100)
    house_number = models.CharField(max_length=20)

    def __str__(self):
        return f"{self.street}, {self.house_number}"

store/forms.py
from django import forms
from django.core.validators import RegexValidator
from django.forms import CheckboxSelectMultiple

from .models import Address, Category, Order


class FiltersForm(forms.Form):
    min_price = forms.FloatField(
        widget=forms.NumberInput(attrs={"value": 0}), required=False, min_value=0
    )
    max_price = forms.FloatField(widget=forms.NumberInput(), required=False)

    categories = forms.ModelMultipleChoiceField(
        queryset=Category.objects.all(), widget=CheckboxSelectMultiple, required=False
    )


class SearchForm(forms.Form):
    search = forms.CharField(
        label="",
        max_length=50,
        required=False,
        widget=forms.TextInput(
            attrs={
                "placeholder": "Type product name here",
                "class": "form-control mb-0 mt-0",
            }
        ),
    )


class OrderForm(forms.ModelForm):
    address = forms.ModelChoiceField(
        queryset=Address.objects.all(), label="Choose shop address."
    )
    phone = forms.CharField(validators=[RegexValidator(r"^\d{7,12}$")])

    class Meta:
        model = Order
        fields = ("address", "phone")

store/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from django.views.generic import TemplateView, DetailView, ListView, View

from store.forms import FiltersForm, OrderForm
from store.models import Product, Cart, CartProduct, Category, Order
from store import forms
from django.contrib.auth.decorators import login_required, permission_required


# Create your views here.


class IndexView(TemplateView):
    template_name = "base.html"

    def get_context_data(self, **kwargs):
        context = super(IndexView, self).get_context_data(**kwargs)
        context["objects"] = Product.objects.select_related("category").filter(
            discount_price__isnull=False
        )
        return context


class ProductDetailView(DetailView):
    model = Product


class ProductListView(ListView):
    model = Product
    paginate_by = 6

    def get_context_data(self, **kwargs):
        context = super(ProductListView, self).get_context_data(**kwargs)
        max_prod_price = Product.objects.order_by("-price").first().price

        query = self.request.GET.copy()
        query.pop("page", None)
        query = query.urlencode()
        print(query)
        filters_form = forms.FiltersForm(self.request.GET)
        if filters_form.is_valid():
            filters_form = forms.FiltersForm(initial=filters_form.cleaned_data)
        if not self.request.GET.get("max_price"):
            filters_form = forms.FiltersForm(initial={"max_price": max_prod_price})

        search_form = forms.SearchForm(self.request.GET)
        if search_form.is_valid():
            search_form = forms.SearchForm(initial=search_form.cleaned_data)

        context["search_form"] = search_form
        context["filters_form"] = filters_form
        context["query"] = query
        return context

    def get_queryset(self):
        queryset = (
            super(ProductListView, self).get_queryset().select_related("category")
        )

        if self.request.GET.get("search"):
            queryset = queryset.filter(name__icontains=self.request.GET.get("search"))

        form = FiltersForm(self.request.GET)
        if form.is_valid() and "min_price" in self.request.GET:
            if form.cleaned_data["categories"]:
                queryset = queryset.filter(
                    category__in=self.request.GET.getlist("categories")
                )

            queryset = queryset.filter(
                price__gte=self.request.GET["min_price"],
                price__lte=self.request.GET["max_price"],
            )
        return queryset


class CategoryView(ListView):
    model = Product
    paginate_by = 6

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CategoryView, self).get_context_data(**kwargs)
        context["category"] = Category.objects.get(slug__exact=self.kwargs.get("slug"))
        return context

    def get_queryset(self):
        queryset = super(CategoryView, self).get_queryset().select_related("category")
        return queryset.filter(category__slug=self.kwargs.get("slug"))


def get_cart(request):
    if not request.session or not request.session.session_key:
        request.session.save()
    if request.session.session_key:
        cart, created = Cart.objects.get_or_create(
            session_key=request.session.session_key, active=True
        )
    else:
        cart, created = Cart.objects.get_or_create(user=request.user, active=True)
    return cart


def get_or_create_cart_product(request, slug):
    cart = get_cart(request)
    product = get_object_or_404(Product, slug=slug)
    cart_product, created = CartProduct.objects.get_or_create(
        cart=cart, product=product
    )
    return cart_product, created


def add_to_cart(request, slug):
    cart_product, created = get_or_create_cart_product(request, slug)
    if not created:
        cart_product.quantity += 1
        cart_product.save()
    return redirect("store:cart_view")


def remove_from_cart(request, slug):
    cart_product, created = get_or_create_cart_product(request, slug)
    if not created and cart_product.quantity > 1:
        cart_product.quantity -= 1
        cart_product.save()
    elif not created:
        cart_product.delete()

    return redirect("store:cart_view")


class CartView(TemplateView):
    template_name = "store/cart_view.html"

    def get_context_data(self, **kwargs):
        cart = get_cart(self.request)
        cart_products = cart.cartproduct_set.select_related("product__category").all()
        context = {
            "cart": cart,
            "cart_products": cart_products,
            "total": cart.get_total(),
        }
        return context


class OrderCheckoutView(TemplateView):
    template_name = "store/order_checkout.html"

    def get_context_data(self, **kwargs):
        context = super(OrderCheckoutView, self).get_context_data(**kwargs)
        order_form = forms.OrderForm()
        context["order_form"] = order_form
        return context

    def post(self, request, *args, **kwargs):
        order_form = forms.OrderForm(request.POST)
        if order_form.is_valid():
            cart = get_cart(self.request)

            order = Order.objects.create(
                cart=cart,
                address=order_form.cleaned_data["address"],
                phone=order_form.cleaned_data["phone"],
            )
            cart.active = False
            cart.save()
            return redirect("store:cart_view")
        else:
            context = {"order_form": order_form}
            return render(request, self.template_name, context)


@permission_required("store.add_order")
def view_orders(request):
    orders = Order.objects.select_related("address", "cart").prefetch_related(
        "cart__cartproduct_set", "cart__cartproduct_set__product"
    )
    context = {
        "orders": orders,
    }
    return render(request, "store/view_orders.html", context=context)

templates/store/cart_view.html
{% extends 'base.html' %}

{% block content %}
  <h1>Your Cart</h1>
  {% if cart.products.exists %}
    <div class="col-auto">
      <table class="table-bordered table table-hover table align-middle">
        <thead>
        <tr class="table-primary">
          <th>Product</th>
          <th>Price</th>
          <th>Quantity</th>
          <th>Total</th>
          <th>Actions</th>
        </tr>
        </thead>
        <tbody>
        {% for product in cart_products %}
          <tr>
            <td class="text-truncate" style="max-width: 320px;">{{ product.product.name }}</td>
            <td>${{ product.product.get_price }}</td>
            <td>{{ product.quantity }}</td>
            <td>${{ product.get_price }}</td>
            <td>
              <a class="btn btn-outline-success" href="{% url 'store:add_to_cart' product.product.slug %}">➕</a>
              <a class="btn btn-outline-danger" href="{% url 'store:remove_from_cart' product.product.slug %}">➖</a>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="5">No products in your cart.</td>
          </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
    <p><strong>Total:</strong> ${{ total }}</p>
    <a href="{% url 'store:checkout_view' %}">Go to checkout</a>
  {% else %}
    <p>No products in your cart.</p>
  {% endif %}
{% endblock %}

templates/store/order_checkout.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}

{% block content %}
  <div class="col-auto">
    <form method="post">
      {% csrf_token %}
      {{ order_form|crispy }}
      <input type="submit" value="Confirm order" class="btn btn-success">
    </form>
  </div>
{% endblock content %}

templates/store/product_detail.html
{% extends 'base.html' %}

{% block breadcrumbs %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'store:index' %}">Home</a></li>
      <li class="breadcrumb-item"><a href="{{ object.category.get_absolute_url }}">{{ object.category.name }}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{{ object.name }}</li>
    </ol>
  </nav>
{% endblock breadcrumbs %}


{% block content %}
  <div class="container">
    <div class="row">
      <div class="col-md-6">
        <img src="{{ product.image.url }}" class="img-fluid" alt="{{ product.name }}">
      </div>
      <div class="col-md-6">
        <h2>{{ product.name }}</h2>
        <p>{{ product.description }}</p>
        {% if product.discount_price %}
          <h4 class="text-danger text-decoration-line-through fs-3">{{ product.price }}</h4>
        {% endif %}
        <p class="fs-2"><strong>Price:</strong> {{ product.get_price }}</p>
        <a class="btn btn-primary" href="{% url 'store:add_to_cart' product.slug %}">Add to Cart</a>
      </div>
    </div>
  </div>
{% endblock %}

templates/store/product_list.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load static %}
{% load crispy_forms_tags %}

{% block navbar %}
  {% include 'includes/navbar.html' with search_form=search_form %}
{% endblock navbar %}


{% block sidebar %}
  <div class="ps-5 col-3">
    {% if filters_form %}
      <form id="product_list_form" action="" method="get">
        {{ filters_form|crispy }}
        {{ search_form|crispy }}
        <input form="product_list_form" value="Apply" type="submit" class="btn btn-outline-success">
      </form>
      <a type="button" class="btn btn-outline-danger mt-2" href="{% url 'store:product_list' %}">Reset</a>
    {% endif %}
    {% if category %}
      <h3>{{ category.name }}</h3>
      {% if category.description %}
        <p>{{ category.description }}</p>
      {% endif %}

    {% endif %}


  </div>
{% endblock sidebar %}

{% block content %}
  <div class="col-8">
    <div class="row">
      {% for product in product_list %}
        <div class="col-xl-4 col-lg-4 col-md-6 col-sm-auto mb-4">
          {% include 'includes/product_card.html' with product=product %}
        </div>
      {% empty %}
        <h3>Empty</h3>
      {% endfor %}
    </div>
  </div>


{% endblock content %}

templates/store/view_orders.html
{% extends 'base.html' %}
{% block content %}
  {% for order in orders %}
    <h2>Order - {{ order.id }}</h2>
    <p>Address: {{ order.address }}</p>
    <p>Phone: {{ order.phone }}</p>
    <p>Status: {{ order.status }}</p>
    <h3>Products:</h3>
    <ul>
      {% for product in order.cart.cartproduct_set.all %}
        <li>
          {{ product }} - quantity: {{ product.quantity }} (price: {{ product.get_price }})
        </li>
      {% endfor %}
    </ul>
  {% endfor %}
{% endblock content %}